export const BudgetCategory = {
  VENUE: "VENUE",
  CATERING: "CATERING",
  DECORATION: "DECORATION",
  PHOTOGRAPHY: "PHOTOGRAPHY",
  ENTERTAINMENT: "ENTERTAINMENT",
  MUSIC: "MUSIC",
  FLOWERS: "FLOWERS",
  ATTIRE: "ATTIRE",
  TRANSPORTATION: "TRANSPORTATION",
  OTHER: "OTHER",
};

export const BUDGET_CATEGORIES = Object.values(BudgetCategory);
