
export const EventCategoryEnum = Object.freeze({
  WEDDING: 'WEDDING',
  BIRTHDAY: 'BIRTHDAY',
  CORPORATE: 'CORPORATE',
  CONFERENCE: 'CONFERENCE',
  DINNER: 'DINNER',
  BABY_SHOWER: 'BABY_SHOWER',
  GRADUATION: 'GRADUATION',
  ANNIVERSARY: 'ANNIVERSARY',
  GALLERY: 'GALLERY'
});
