export const PackageCategoryEnum = Object.freeze({
  WEDDING: 'WEDDING',
  BIRTHDAY: 'BIRTHDAY',
  ENGAGEMENT: 'ENGAGEMENT',
  CORPORATE: 'CORPORATE',
  BABY_SHOWER: 'BABY_SHOWER',
  OTHER: 'OTHER',
  GALLERY: 'GALLERY',
  ORGANIZER: 'ORGANIZER',
  VENDOR: 'VENDOR'
});
