export const PackageTypeEnum = Object.freeze({
  INV_BASIC: 'INV_BASIC',
  INV_PRO: 'INV_PRO',
  INV_PREMIUM: 'INV_PREMIUM',
  GALLERY_BASIC: 'GALLERY_BASIC',
  GALLERY_PREMIUM: 'GALLERY_PREMIUM',
  ORGANIZER: 'ORGANIZER'
});
