<template>
  <section class="credentials" :aria-label="t('checkin.credentials')">
    <header class="pane-head">
      <h2>{{ t('checkin.credentials') }}</h2>
      <input
        v-model="search"
        class="search"
        type="search"
        :placeholder="t('checkin.searchGuests')"
        :aria-label="t('checkin.searchGuests')"
      />
    </header>

    <p class="note">{{ t('checkin.credentialsNote') }}</p>

    <ul class="list">
      <li v-for="guest in visible" :key="guest.id" :data-guest-id="guest.id">
        <span class="name">{{ guest.name }}</span>
        <span v-if="stateOf(guest.id)" class="state" :class="stateOf(guest.id).cls">
          {{ stateOf(guest.id).label }}
        </span>
        <button class="link-btn" :disabled="busyId === guest.id" @click="issue(guest)">
          {{ hasLive(guest.id) ? t('checkin.reissue') : t('checkin.issue') }}
        </button>
        <button
          v-if="hasLive(guest.id)"
          class="link-btn danger"
          :disabled="busyId === guest.id"
          @click="revoke(guest)"
        >
          {{ t('checkin.revoke') }}
        </button>
      </li>
    </ul>

    <p v-if="error" class="error" role="alert">{{ error }}</p>

    <!-- The token is shown once and nowhere stored. Asking again mints a new
         one that kills this one, which is the honest cost of not keeping a
         copy — a token held in a database is a token that leaks with it. -->
    <div v-if="issued" class="issued">
      <h3>{{ issued.guestName }}</h3>
      <img v-if="qrDataUrl" class="qr" :src="qrDataUrl" :alt="t('checkin.qrAlt', { name: issued.guestName })" />
      <p class="once">{{ t('checkin.shownOnce') }}</p>
      <button class="link-btn" @click="issued = null">{{ t('checkin.close') }}</button>
    </div>
  </section>
</template>

<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import QRCode from 'qrcode'
import { checkinService } from '@/services/checkin.service'

const props = defineProps({
  eventId: { type: String, required: true },
  guests: { type: Array, default: () => [] },
})

const { t } = useI18n()

const credentials = ref([])
const search = ref('')
const busyId = ref(null)
const issued = ref(null)
const qrDataUrl = ref('')
const error = ref('')

function unwrap(response) {
  return response?.data ?? response ?? null
}

onMounted(refresh)

async function refresh() {
  try {
    credentials.value = unwrap(await checkinService.credentials(props.eventId, 'CHECKIN')) || []
  } catch (e) {
    error.value = e?.detail || e?.message || ''
  }
}

const visible = computed(() => {
  const term = search.value.trim().toLowerCase()
  if (!term) return props.guests
  return props.guests.filter(g => (g.name || '').toLowerCase().includes(term))
})

function liveFor(guestId) {
  return credentials.value.find(c => c.guestId === guestId && !c.revokedAt)
}

function hasLive(guestId) {
  return Boolean(liveFor(guestId))
}

/** Says what the guest is holding, so "reissue" is an informed choice. */
function stateOf(guestId) {
  const live = liveFor(guestId)
  if (live) {
    return live.issueNumber > 1
      ? { cls: 'reissued', label: t('checkin.codeNumber', { n: live.issueNumber }) }
      : { cls: 'live', label: t('checkin.codeLive') }
  }
  const anyRevoked = credentials.value.some(c => c.guestId === guestId)
  return anyRevoked ? { cls: 'revoked', label: t('checkin.codeRevoked') } : null
}

async function issue(guest) {
  busyId.value = guest.id
  error.value = ''
  try {
    const result = unwrap(await checkinService.issueCredential(props.eventId, { guestId: guest.id }))
    issued.value = { ...result, guestName: guest.name }
    await refresh()
  } catch (e) {
    error.value = e?.detail || e?.message || ''
  } finally {
    busyId.value = null
  }
}

async function revoke(guest) {
  busyId.value = guest.id
  error.value = ''
  try {
    await checkinService.revokeCredential(props.eventId, {
      guestId: guest.id,
      reason: t('checkin.revokedByOrganizer'),
    })
    await refresh()
  } catch (e) {
    error.value = e?.detail || e?.message || ''
  } finally {
    busyId.value = null
  }
}

// Rendered on the device rather than fetched: the token is the thing that
// must not travel further than it has to, and a QR image generated by a
// server is one more place it has been.
watch(issued, async (value) => {
  if (!value?.token) {
    qrDataUrl.value = ''
    return
  }
  try {
    qrDataUrl.value = await QRCode.toDataURL(value.token, { width: 260, margin: 1 })
  } catch {
    qrDataUrl.value = ''
  }
})
</script>

<style scoped>
.credentials { padding: 14px; border-radius: 10px; background: #fff; border: 1px solid #ece8e0; }
.pane-head { display: flex; justify-content: space-between; align-items: center; gap: 8px; flex-wrap: wrap; }
.pane-head h2 { margin: 0; font-size: 15px; }
.search { padding: 7px 10px; border: 1px solid #ddd8cf; border-radius: 8px; font-size: 13px; }

.note { margin: 8px 0 10px; font-size: 12px; color: #6b6b6b; }

.list { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 4px; max-height: 340px; overflow-y: auto; }
.list li { display: flex; gap: 8px; align-items: baseline; padding: 6px 8px; border-radius: 6px; }
.list li:hover { background: #faf8f4; }
.name { flex: 1; }

.state { font-size: 11px; padding: 2px 8px; border-radius: 999px; }
.state.live { background: #e6f2e2; color: #2f6b28; }
.state.reissued { background: #fbf1dc; color: #8f6d1f; }
.state.revoked { background: #fdeceb; color: #a3271f; }

.issued { margin-top: 12px; padding: 12px; border-radius: 10px; background: #faf8f4; text-align: center; }
.issued h3 { margin: 0 0 8px; font-size: 14px; }
.qr { width: 220px; height: 220px; }
.once { margin: 8px 0; font-size: 12px; color: #8f6d1f; }

.error { margin: 8px 0 0; font-size: 13px; color: #a3271f; }

.link-btn { border: 0; background: none; color: #5a7a52; cursor: pointer; font-size: 13px; padding: 0; }
.link-btn.danger { color: #a3271f; }
.link-btn:disabled { opacity: 0.5; cursor: default; }
</style>
